export default [
  {
    postName: "Smart IOT Plug",
    postPic: require("../../assets/images/1.png"),
    postVid: require("../../assets/vids/vid3.mp4"),
    userName: "Carlos",
    userPic: require("../../assets/users/user8.jpg"),
    likes: 50,
    comments: 120,
    sold: 12,
  },
  {
    postName: "Servo Robotic Arm",
    postPic: require("../../assets/images/2.png"),
    postVid: require("../../assets/vids/vid4.mp4"),
    userName: "Sam",
    userPic: require("../../assets/users/user6.jpg"),
    likes: 65,
    comments: 100,
    sold: 20,
  },
  // {
  //   postName: "Smart IOT Plug",
  //   postPic: require("../../assets/images/1.png"),
  //   postVid: require("../../assets/vids/vid3.mp4"),
  //   userName: "Carlos",
  //   userPic: require("../../assets/users/user8.png"),
  //   likes: 5,
  //   comments: 10,
  //   sold: 12,
  // },
];
