export default [
  // {
  //   postName: "Smart IOT Plug",
  //   postPic: require("../../assets/images/1.png"),
  //   postVid: require("../../assets/vids/vid3.mp4"),
  //   userName: "Carlos",
  //   userPic: require("../../assets/users/user8.jpg"),
  //   likes: 50,
  //   comments: 120,
  //   sold: 12,
  // },
  // {
  //   postName: "Servo Robotic Arm",
  //   postPic: require("../../assets/images/2.png"),
  //   postVid: require("../../assets/vids/vid4.mp4"),
  //   userName: "Sam",
  //   userPic: require("../../assets/users/user6.jpg"),
  //   likes: 65,
  //   comments: 100,
  //   sold: 20,
  // },
  {
    postName: "Servo Robotic Arm",
    postPic: require("../../assets/images/7.png"),
    postVid: require("../../assets/vids/vid0.mp4"),
    userName: "Raymond",
    userPic: require("../../assets/users/user5.jpg"),
    likes: 35,
    comments: 120,
    sold: 24,
  },
  {
    postName: "Servo Robotic Arm",
    postPic: require("../../assets/images/2.png"),
    postVid: require("../../assets/vids/vid1.mp4"),
    userName: "Harley",
    userPic: require("../../assets/users/user7.jpg"),
    likes: 52,
    comments: 153,
    sold: 33,
  },
  {
    postName: "Servo Robotic Arm",
    postPic: require("../../assets/images/9.png"),
    postVid: require("../../assets/vids/vid2.mp4"),
    userName: "Keisha",
    userPic: require("../../assets/users/user9.jpg"),
    likes: 32,
    comments: 453,
    sold: 13,
  },
  {
    postName: "Servo Robotic Arm",
    postPic: require("../../assets/images/9.png"),
    postVid: require("../../assets/vids/vid5.mp4"),
    userName: "Keisha",
    userPic: require("../../assets/users/user9.jpg"),
    likes: 32,
    comments: 453,
    sold: 13,
  },
  // {
  //   postName: "Servo Robotic Arm",
  //   postPic: require("../../assets/images/9.png"),
  //   postVid: require("../../assets/vids/vid6.mp4"),
  //   userName: "Keisha",
  //   userPic: require("../../assets/users/user9.jpg"),
  //   likes: 32,
  //   comments: 453,
  //   sold: 13,
  // },
];
