export default [
  {
    user: "Jane",
    userPic: require("../../assets/users/user8.jpg"),
    comment: "This is very cool!",
    like: 0,
    seen: 0,
  },
  {
    user: "Marie",
    userPic: require("../../assets/users/user11.jpg"),
    comment: "This is very cool!",
    like: 1,
    seen: 0,
  },
  {
    user: "Mel",
    userPic: require("../../assets/users/user7.jpg"),
    comment: "This is Interesting!",
    like: 1,
    seen: 0,
  },
  {
    user: "Sam",
    userPic: require("../../assets/users/user6.jpg"),
    comment: "Wow awesome!",
    like: 0,
    seen: 0,
  },
  {
    user: "Rebecca",
    userPic: require("../../assets/users/user5.jpg"),
    comment: "That's incredible!",
    like: 1,
    seen: 0,
  },
  {
    user: "Carlos",
    userPic: require("../../assets/users/user4.jpg"),
    comment: "This is very cool!",
    like: 1,
    seen: 0,
  },
  {
    user: "Ferry",
    userPic: require("../../assets/users/user3.jpg"),
    comment: "This is Interesting!",
    like: 0,
    seen: 1,
  },
  {
    user: "Chris",
    userPic: require("../../assets/users/user2.jpg"),
    comment: "Wow awesome!",
    like: 0,
    seen: 1,
  },
  {
    user: "Carlos",
    userPic: require("../../assets/users/user4.jpg"),
    comment: "This is very cool!",
    like: 1,
    seen: 1,
  },
  {
    user: "Thadeo",
    userPic: require("../../assets/users/user1.jpg"),
    comment: "That's incredible!",
    like: 1,
    seen: 1,
  },
  {
    user: "Neta",
    userPic: require("../../assets/users/user9.jpg"),
    comment: "Wow awesome!",
    like: 1,
    seen: 1,
  },
  {
    user: "Stiven",
    userPic: require("../../assets/users/user10.jpg"),
    comment: "That's incredible!",
    like: 0,
    seen: 1,
  },
  {
    user: "Marie",
    userPic: require("../../assets/users/user11.jpg"),
    comment: "This is very cool!",
    like: 1,
    seen: 1,
  },
  {
    user: "Sam",
    userPic: require("../../assets/users/user6.jpg"),
    comment: "Wow awesome!",
    like: 0,
    seen: 1,
  },
  {
    user: "Thadeo",
    userPic: require("../../assets/users/user1.jpg"),
    comment: "This is Interesting!",
    like: 0,
    seen: 1,
  },
  {
    user: "Chris",
    userPic: require("../../assets/users/user2.jpg"),
    comment: "Wow awesome!",
    like: 0,
    seen: 1,
  },
  {
    user: "Ferry",
    userPic: require("../../assets/users/user3.jpg"),
    comment: "This is Interesting!",
    like: 0,
    seen: 1,
  },
];
